id: ID5E35EAB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-10T08:39:43+00:00'
last_modified: '2022-06-09T17:53:14.489579+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18292
  title: བོད་ཀྱི་གནའ་རབས་ལོ་རྒྱུས་བདམས་བཏུས་གངས་ལྗོངས་འོད་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    80F7:
      image_group_id: I1KG18418
      title: Volume 1 of bod kyi gna' rabs lo rgyus bdams btus gangs ljongs 'od 'bum/
      total_pages: 274
      order: 1
      base_file: 80F7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
